### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by kandikits**
Hello - request review and approval on the inclusion of Explore JavaScript on your list.
It would be a good addition under FRAMEWORKS AND LIBRARIES section of this article. Would you like to include it in your list? We'd love to hear your feedback.
Thanks!

### CODE REVIEW

**Comment by kostasx** [comment]
I would love to discuss about including this in the list @kandikits, but it might be confusing for newcomers to find results under the [explore-libraries](https://kandi.openweaver.com/explore/javascript/explore-libraries) web page that are not actually libraries, for example freeCodecamp, 30-seconds-of-code, awesome-selfhosted, etc.

Great resources, nevertheless, they are not libraries.

**Comment by kandikits** [comment]
Thanks @kostasx, for your candid feedback.

However, we have analyzed that pages like https://kandi.openweaver.com/explore/javascript, learners visit the most and found it useful, because it has Learning Resources, Trending Discussion, top authors along with libraries and code snippets, etc.. 

Would you still want to reconsider to include this page under '3.1 BEGINNER RESOURCES' instead? We could help promote your list on Social Media as a token of appreciation.

**Comment by kostasx** [comment]
@kandikits Under what title would you suggest this link is included?

**Comment by kandikits** [comment]
Title could be like:

[3. Resources]
  [3.1 Beginner Resources]
    [3.1.1 Courses]
    [3.1.2 Testing Code]
    [3.1.3 APIs]
    [3.1.4 Other Resources] OR 'Misc. Resources'

**Comment by kostasx** [comment]
Oh, no! I meant, every resources has a title and a link, e.g. Style Guide (title) => https://github.com/airbnb/javascript (link).
So what would be the title for your link under Beginner Resources? @kandikits 
(title) ? => https://kandi.openweaver.com/explore/javascript (link)

**Comment by kandikits** [comment]
Oh okay that ways, may be the title could be 'Explore JavaScript' OR 'Discover JavaScript' OR 'JS Resources', something like that....? Your views?

**Comment by kostasx** [comment]
Done! Just added it under [General Resources](https://github.com/kostasx/LearnJavascript/#32-general). 😉

**Comment by kandikits** [comment]
Thanks @kostasx. 
If there a Tweet OR a LinkedIn post, you want us to promote - pls do share a link.

**Pull request closed without merging**
